### ISSUE TITLE
esVKA tokens in the LP contract can be converted out for PSM, denying compounding

### ISSUE THREAD

**Issue by carrotsmuggler** [shieldify-security/Portals-810fd90645cccf6fd80d91f8050eff618f63af81#25]
## Severity

Low

## Description

esVKA tokens in the LP contract can be converted out for PSM, denying compounding

## Impact

Lower rewards due to denied compounding

## Attack Scenario

Staking tokens in `SINGLE_STAKING` rewards the staker with esVKA tokens. The protocol is designed to collect these esVKA tokens and stake them on the `DUAL_STAKING` vault. This is done via the `claimProtocolRewards` function.

```solidity
uint256 esVKABalance = IERC20(esVKA).balanceOf(address(this));
if (esVKABalance > 0) {
    IDualStaking(DUAL_STAKING).stake(esVKABalance, esVKA);
}
```

The contract receives esVKA tokens whenever it deposits to the `SINGLE_STAKING` vault. So if a user stakes tokens in the Portal, the virtual LP will eventually call `stake` on the `SINGLE_STAKING` vault and receive some esVKA tokens which have been accrued till now.

The issue is that any user can come in and call the `convert` function to buy out the esVKA tokens for PSM tokens. Thus denying the ability of the protocol to instead stake them on `DUAL_STAKING` for even more rewards.

## Proof of Concept (PoC)

Can be recreated in the following steps:

1. Stake some amount in the Portal. `SINGLE_STAKING` will pay out the currently accrued esVKA tokens to the virtual LP.
2. Call the `convert` function to buy out the esVKA tokens for PSM tokens.

## Location of Affected Code

https://github.com/shieldify-security/Portals-810fd90645cccf6fd80d91f8050eff618f63af81/blob/30129e4ce71a379e0bc62a93c245e5898331028e/src/V2MultiAsset/VirtualLP.sol#L502-L568

## Recommendation

Consider denying esVKA tokens from the `convert` function.

**Comment by PossumLabsCrypto** [comment]
esVKA is a non-transferrable token. More precisely, it can only be transferred to allowed addresses, such as the Dual Staking contract but not between users.

The only thing a malicious actor could do is to call convert() with the Dual Staking contract as receiver which would effectively perma-lock the esVKA. However, this does not benefit the attacker but to the contrary benefit the protocol because the attacker must pay PSM.

All that being said, even if it was possible as described above it would just be a regular convert() call that benefits the protocol as intended, hence no issue here.
